### ISSUE TITLE
Passing pre-processor variables

### ISSUE THREAD

**Issue by wlievens** [andi12/msbuild-maven-plugin#27]
I would like to pass additional pre-processor variables. If I am not mistaken, msbuild.exe supports this (e.g. http://stackoverflow.com/questions/479979/msbuild-defining-conditional-compilation-symbols). I can't find a way to do it in the plugin as is...

**Comment by andi12** [comment]
I think you can achieve what you want with the following XML:
```xml
                    <msbuildPropertys>
                        <msbuildProperty>DefineConstants="MYSYMBOL1;MYSYMBOL2"</msbuildProperty>
                    </msbuildPropertys>
```
I haven't had a chance to test - if you don't mind trying let me know if it works or not and I can look some more.

cheers,
Andi

**Comment by wlievens** [comment]
I've used a different method to solve this, since `DefineConstants` does not allow specifying a value for the variables. I now generate a `build.h` header from my maven script, with the version number inside.

**Comment by andi12** [comment]
Great that you have a solution. The plugin includes VersionInfoMojo, however this only generates an rc file and not a header. However you could generate a .rc and #include it to get the same outcome.
